// Scans src/data/posts/ and regenerates src/data/posts.js with a static
// import for each post file. Wired to `predev` and `prebuild` so adding a
// new post only requires dropping a file in src/data/posts/ — the next
// `bun dev` or `bun run build` picks it up.

import { readdir, writeFile } from 'node:fs/promises';
import { join, dirname, basename, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const postsDir = join(here, '..', 'src', 'data', 'posts');
const outFile = join(here, '..', 'src', 'data', 'posts.js');

function toIdent(filename) {
  const base = basename(filename, extname(filename));
  return base
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part, i) =>
      i === 0
        ? part[0].toLowerCase() + part.slice(1)
        : part[0].toUpperCase() + part.slice(1)
    )
    .join('');
}

const entries = (await readdir(postsDir).catch((err) => {
  if (err.code === 'ENOENT') return [];
  throw err;
}))
  .filter((f) => f.endsWith('.js'))
  .sort();

const imports = entries
  .map((f) => `import ${toIdent(f)} from './posts/${f}';`)
  .join('\n');

const rawArray = entries.map(toIdent).join(', ');

const contents = `// AUTO-GENERATED by scripts/generate-posts.js. Do not edit by hand.
// Drop a new file in src/data/posts/ and run \`bun dev\` or \`bun run build\`.
${imports}
import { parseMarkdown, readingTime } from '../lib/markdown.js';

const raw = [${rawArray}];

export const posts = raw
  .map((source) => {
    const parsed = parseMarkdown(source);
    return {
      ...parsed.frontmatter,
      tags: parsed.frontmatter.tags || [],
      readingTime: readingTime(source),
      blocks: parsed.blocks
    };
  })
  .sort((a, b) => (a.date < b.date ? 1 : -1));

export function getPost(slug) {
  return posts.find((p) => p.slug === slug);
}
`;

await writeFile(outFile, contents);
console.log(`Generated ${outFile} with ${entries.length} post(s)`);
